version: '3'

networks:
  compose-gitops:
    name: compose-gitops

services:
  compose-gitops:
    build:
      context: .
      dockerfile: Dockerfile  
    container_name: compose-gitops
    networks:
      - compose-gitops
    volumes:
      - ./repositories.yaml:/src/repositories.yaml
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # For persistent storage, map the location with deploy folder
      - /tmp/test:/deploy
    restart: unless-stopped