version: '3'

networks:
  compose-gitops:
    name: compose-gitops

services:
  compose-gitops:
    image: redsh4d0w/compose-gitops:cg-ad099c7
    container_name: compose-gitops
    environment:
      - SYNC_TIMEOUT=1 # Default timeout is 5min
    networks:
      - compose-gitops
    volumes:
      - ./repositories.yaml:/src/repositories.yaml
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # For persistent storage, map the location with deploy folder
      - /tmp/test:/deploy
    restart: unless-stopped