version: '3'

networks:
  compose-gitops:
    name: compose-gitops

services:
  compose-gitops:
    image: unixnomad/compose-gitops:cg-67febbd
    container_name: compose-gitops
    environment:
      - SYNC_TIMEOUT=1 # Default timeout is 5min
    env_file:
      - .env
    networks:
      - compose-gitops
    volumes:
      - ./repositories.yaml:/src/repositories.yaml
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # For persistent storage, map the location with deploy folder
      - /tmp/test:/deploy
      # For private repositories
      # - ~/.docker/config.json:/root/.docker/config.json:ro
    restart: unless-stopped