name: "Build and Push to AWS ECR"
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'utils/deploy/docker-compose.yaml'

jobs:
  build:
    name: "Build and Push to ECR"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build, tag
        id: build-image
        env:
          ECR_REGISTRY: ECR_REGISTRY_NAME
          ECR_REPOSITORY: ECR_REPOSITORY_NAME
        run: |
          IMAGE_TAG=bw-$(git rev-parse --short HEAD)
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          echo "image_tag=$IMAGE_TAG" >> "$GITHUB_OUTPUT"
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> "$GITHUB_OUTPUT"

      - name: Scan image
        uses: anchore/scan-action@v3
        with:
          image: ${{ steps.build-image.outputs.image }}
          fail-build: true
          severity-cutoff: critical
          output-format: table
        continue-on-error: true

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}
          aws-region: REGION_NAME

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: push image to Amazon ECR 
        env:
          IMAGE_NAME: ${{ steps.build-image.outputs.image }}
        id: push-image
        run: |
          docker push $IMAGE_NAME

      - name: Deployment Update
        env:
          IMAGE_NAME: ${{ steps.build-image.outputs.image }}
          IMAGE_TAG: ${{ steps.build-image.outputs.image_tag }}
        run: |
            CURRENT_TAG=$(cat docker-compose.yaml | grep -i image| awk -F ':' '{print $NF}')
            sed -i "s/$CURRENT_TAG/$IMAGE_TAG/" docker-compose.yaml

            git config --global user.email "user@github.com"
            git config --global user.name "Git Actions"
            git add .
            git commit -m "[Deployment commit] $IMAGE_TAG"
            git push